### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by jiege6-66** [anasfanani/Magisk-Tailscaled#23]

**Comment by jiege6-66** [comment]
I successfully  operate the tailsclae on kernelsu however,when I want to Access 192.168.2.1, its unable to access, can connect when I enter the virtual ip in tailsclae. How can I fix this?

Also, when I want to share hotspots with other machines，Connected devices can use the Subnet routers？If cant，how to access it ?

**Comment by anasfanani** [comment]
New build should fix subnet routes issue.

> Connected devices can use the Subnet routers?

I'm not sure about this, not yet test

**Comment by anasfanani** [comment]
Yes client can use subnet routes.
Execute this to make tailnet/subnet routes accessible to Wi-Fi client.

```
iptables -t nat -A POSTROUTING -o tailscale0 -j MASQUERADE
```

Let me know if your problem is already solved.

**Comment by ppllpig** [comment]
> Yes client can use subnet routes. Execute this to make tailnet/subnet routes accessible to Wi-Fi client.
> 
> ```
> iptables -t nat -A POSTROUTING -o tailscale0 -j MASQUERADE
> ```
> 
> Let me know if your problem is already solved.


reply: no command ipatable found,...

**Comment by ppllpig** [comment]
> > Yes client can use subnet routes. Execute this to make tailnet/subnet routes accessible to Wi-Fi client.
> > ```
> > iptables -t nat -A POSTROUTING -o tailscale0 -j MASQUERADE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if your problem is already solved.
> 
> reply: no command ipatable found,...

i tried commade su,it worked.but still cannot connect through sub route using local ip like 192.168..

**Comment by fankes** [comment]
```
tailscale up --accept-routes=true
```

Try this? I fixed this issue with this command.

**Comment by fankes** [comment]
According to my own attempts, I can use the following two commands.
First, allow the subnet.

```
tailscale up --accept-routes=true
```

or

```
tailscale up --accept-routes
```

Then set the iptables rules like @ppllpig (need to be reset every time the device is restarted).

```
iptables -t nat -A POSTROUTING -o tailscale0 -j MASQUERADE
```

**Comment by harryxmin** [comment]
any updates on this? im having the same issue. tried the iptables command. still no luck. with the android app, i can reach with 192.168.1.0/24 range. with the magisk module, i can only reach with 100.64.0.0 subnet

**Comment by TigerBeanst** [comment]
```
iptables -t nat -A POSTROUTING -o tailscale0 -j MASQUERADE
```
doesnot work for me too...

**Comment by 2mc** [comment]
Same issue here.
The above proposed procedure has no effect. Subnets remain unreachable. 

> According to my own attempts, I can use the following two commands. First, allow the subnet routers.
> 
> ```
> tailscale up --accept-routes=true
> ```
> 
> or
> 
> ```
> tailscale up --accept-routes
> ```
> 
> Then set the iptables rules like [@ppllpig](https://github.com/ppllpig) (need to be reset every time the device is rebooted).
> 
> ```
> iptables -t nat -A POSTROUTING -o tailscale0 -j MASQUERADE
> ```

**Comment by anasfanani** [comment]
Hi bro, recenty i do modification on tailscale binary itself rather than wrapping command, would you try my latest release ?https://github.com/anasfanani/Magisk-Tailscaled/releases/latest

I have tested in my android 15 and 16.

Basic feature such as DNS, exit-node, ssh, etc its working.

For headscale its untested.

For me its enough testing some basic feature, I need some feedback is there any error, I will try fix directly
